name: Deploy Flask API

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Execute SSH commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        script: |
          cd stockpitcherapi
          git pull
          source venv/bin/activate
          pip install -r requirements.txt
          rm -rf instance/stocks.db
          flask import-data all_stocks_data.csv
          echo ${{ secrets.VPS_PASSWORD }} | sudo -S sudo systemctl restart stockpitcher.service